name: Workflow for internal PRs

on:
  pull_request:
    branches:
      origin/dev-bpolania/workflows

jobs:
  Timestamp:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main
    
  build_and_test:
    needs: [Timestamp]
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-build-unit-test-workflow.yml@origin/bpolania/workflows
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      ENVIRONMENT: "beta-sepolia"
    secrets:
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}
    
