name: Workflow for internal PRs

on:
  push:
    branches:
      - main
      - dev
      - v1.1
      - dev_v1.1

  pull_request:
    branches:
      - main
      - dev
      - v1.1
      - dev_v1.1

jobs:
  Timestamp:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  build_and_test:
    needs: [Timestamp]
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-build-unit-test-workflow.yml@origin/bpolania/workflows
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      ENVIRONMENT: "odyssey"
