name: Workflow for Merge

on:
  push:
    branches:
      - origin/dev-bpolania/workflows

jobs:
  build_and_test:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-build-integration-test-workflow.yml@origin/bpolania/workflows
    with:
      sha: ${{ github.sha }}
      ENVIRONMENT: "beta-sepolia"
    secrets:
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}
    
